### ISSUE TITLE
Add spatial and temporal resolution? 

### ISSUE THREAD

**Issue by adammwilson** [samapriya/Earth-Engine-Datasets-List#1]
Feature request:  Would it be possible to add columns for the spatial and temporal resolution (and perhaps the spatial domain - outer bounding box)? Also, it would be great if any [tags](https://developers.google.com/earth-engine/datasets/tags/) were also included (perhaps as a delimited list in a single column (e.g. elevation_lidar).

**Comment by samapriya** [comment]
Hi, @adammwilson I run the scripts once every week to get both raster and vector data in the Catalog. For me to get the spatial and temporal resolution, I would need to process just the raster data and the same applies to tags. So I do not intend to integrate that in the dataset list. But thank you for your suggestions.

**Comment by samapriya** [comment]
Hey @adammwilson ,
I am happy to say that I am able to give you one of the things on your wishlist, the next release of the data will have a comma separated tags column. Hope that helps
