### ISSUE TITLE
the difference of end_date and endyear

### ISSUE THREAD

**Issue by qq2898** [samapriya/Earth-Engine-Datasets-List#2]
as the first record shows:
start_date | end_date   | startyear | endyear
10/01/92  | 2004/4/20 | 1992        | 2020
while the website said:
       Dataset Availability
           1992-10-02T00:00:00 - Present
is there any mistakes in end_date ?

thank you.

**Comment by samapriya** [comment]
Yeah, the date consistency has been broken a bit. You can read the [discussion here](https://groups.google.com/forum/#!topic/google-earth-engine-developers/gpYj1-BLvxw). This might take more time and effort to fix for now. Open to suggestions

**Comment by samapriya** [comment]
This issue is fixed in today's release. Closing this for now
