### ISSUE TITLE
New GEE STAC structure

### ISSUE THREAD

**Issue by davemlz** [samapriya/Earth-Engine-Datasets-List#4]
Hey, @samapriya!

I know you also work a lot with the GEE STAC and that the new 3-level structure just broke a lot of things, so I created this [flattened list of collections with no levels](https://github.com/davemlz/ee-flatten) for my projects, maybe it can be also useful for you!

Cheers,

Dave

**Comment by samapriya** [comment]
Thanks @davemlz 
Will definitely take a look appreciate the support :)

**Comment by samapriya** [comment]
Finally just ended up writing an iterator so it can handle any number of layers thanks for the quick input on this @davemlz closing the issue after I tested the result
